name: Github-SNK

on:
  schedule: [{cron: "0 0 */7 * *"}] #每七天更新一次
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/snk.yml'  #配置改动时执行
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
     - name: Generate svg
       uses: Platane/snk@v3
       with:
         # github user name to read the contribution graph from (**required**)
         # using action context var `github.repository_owner` or specified user
         github_user_name: ${{ github.repository_owner }}
     
         # list of files to generate.
         # one file per line. Each output can be customized with options as query string.
         #
         #  supported options:
         #  - palette:           A preset of color, one of [github, github-dark, github-light]
         #  - color_snake:       Color of the snake
         #  - color_dots:        Coma separated list of dots color.
         #                       The first one is 0 contribution, then it goes from the low contribution to the highest.
         #                       Exactly 5 colors are expected.
         #  - color_background:  Color of the background (for gif only)
         outputs: |
           ./snake/github-snake.svg
           ./snake/github-snake-dark.svg?palette=github-dark
           ./snake/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

     - name: Commit and push changes
       working-directory: ${{ github.workspace }}
       run: |
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         
         git add snake/
         
         if git diff --staged --quiet; then
           echo "No changes to commit"
         else
           git commit -m "update github snake animation"
           git push
         fi